// Optional end-to-end acceptance: npm install --no-save playwright, then node tests/browser.cjs.
const {chromium}=require('playwright');
const {spawn}=require('node:child_process');
const {mkdirSync,readFileSync}=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),artifacts=path.join(root,'artifacts');mkdirSync(artifacts,{recursive:true});
(async()=>{
 const server=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:'3187'},stdio:['ignore','pipe','pipe']});
 await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',()=>reject(Error('Test server exited')));});
 const browser=await chromium.launch({executablePath:process.env.QA_CHROMIUM||undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process','--disable-gpu']});
 const errors=[],context=await browser.newContext({viewport:{width:1440,height:1100}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 const all=store=>page.evaluate(async store=>{const {readAll}=await import('/storage.mjs');return readAll(store);},store);
 const nav=async name=>page.locator(`[data-view="${name}"]`).click();
 const waitSaved=async count=>{const end=Date.now()+20000;while((await all('takes')).length!==count){if(Date.now()>end)throw Error('Timed out waiting for '+count+' saved takes');await page.waitForTimeout(60);}};
 try{
  await page.goto('http://127.0.0.1:3187');await page.waitForSelector('#score-viewer svg');assert.equal(await page.locator('#library-count').innerText(),'9');await page.screenshot({path:path.join(artifacts,'desktop-v2.png'),fullPage:true});
  await nav('library');assert.equal(await page.locator('.score-tile').count(),9);await page.locator('[data-filter="车尔尼"]').click();assert.equal(await page.locator('.score-tile').count(),2);assert.equal(await page.locator('.score-cover.czerny').count(),2);await page.locator('[data-open-score="czerny-599-1"]').click();assert.match(await page.locator('#piece-title').innerText(),/599/);assert.equal(await page.locator('#end-bar').inputValue(),'16');await page.waitForFunction(()=>document.querySelectorAll('#score-viewer .vf-stavenote').length>50);
  await page.locator('#zoom-in').click();assert.equal(await page.locator('#zoom-value').innerText(),'110%');await page.locator('#focus-button').click();assert(await page.locator('body').evaluate(e=>e.classList.contains('focus-mode')));await page.keyboard.press('Escape');assert(!await page.locator('body').evaluate(e=>e.classList.contains('focus-mode')));
  await nav('library');await page.locator('[data-filter="哈农"]').click();assert.equal(await page.locator('.score-tile').count(),2);await page.locator('[data-open-score="hanon-1"]').click();await page.locator('#practice-hand').selectOption('right');await page.locator('#end-bar').fill('1');await page.locator('#end-bar').dispatchEvent('change');await page.locator('#tempo-number').fill('240');await page.locator('#tempo-number').dispatchEvent('change');assert.equal(await page.locator('#duration').innerText(),'00:00'); // 2 quarter beats = 0.5s
  console.log('PASS: nine-score library, Czerny/Hanon filters, notation, hand/range, zoom and focus');
  await page.locator('#demo-button').click();await page.waitForSelector('#feedback-content .metrics',{timeout:6000});await waitSaved(1);let saved=await all('takes');assert.equal(saved[0].source,'demo');assert.equal(saved[0].score.id,'hanon-1');assert.equal(saved[0].options.hand,'right');assert.equal(saved[0].options.endBar,1);assert.match(await page.locator('.result-badge').innerText(),/模拟/);assert.equal(await page.locator('#history-count').innerText(),'0');
  await page.screenshot({path:path.join(artifacts,'feedback-v2.png'),fullPage:true});
  await page.reload();await page.waitForSelector('#score-viewer svg');await nav('history');assert.equal(await page.locator('.history-row').count(),0);await page.locator('[data-take-filter="all"]').click();assert.equal(await page.locator('.history-row').count(),1);await page.locator('.history-row').click();assert.match(await page.locator('.result-badge').innerText(),/模拟/);assert.equal(await page.locator('#end-bar').inputValue(),'1');
  console.log('PASS: demo capture → scored snapshot → separate statistics → persistence → restore');
  await page.locator('#virtual-button').click();await page.locator('#tempo-number').fill('120');await page.locator('#tempo-number').dispatchEvent('change');await page.locator('#start-button').click();await page.waitForFunction(()=>document.querySelector('#capture-status').textContent.includes('正在采集'));await page.keyboard.press('a');await page.keyboard.press('s');await page.locator('#start-button').click();await waitSaved(2);saved=(await all('takes')).find(t=>t.source==='virtual');assert.deepEqual(saved.events.map(n=>n.pitch),[60,62]);assert(saved.interrupted);assert.match(await page.locator('.result-warning').innerText(),/主动结束/);
  await page.locator('#start-button').click();await page.locator('#start-button').click();assert.equal((await all('takes')).length,2);
  await page.locator('#start-button').click();await page.waitForFunction(()=>document.querySelector('#capture-status').textContent.includes('正在采集'));await page.locator('#start-button').click();await waitSaved(3);assert.equal(await page.locator('#feedback-content .metrics').count(),0);assert.match(await page.locator('#feedback-content').innerText(),/没有听见/);
  console.log('PASS: keyboard events with button focus, partial take, cancelled countdown and empty result');
  await nav('library');await page.locator('#create-score').click();await page.waitForSelector('#editor-sheet svg');await page.locator('#ed-title').fill('QA 图形双手练习');await page.locator('#ed-title').dispatchEvent('change');const grid=page.locator('.roll-grid');await grid.click({position:{x:24,y:24*19+9}});assert.equal(await page.locator('.roll-note').count(),1);await page.locator('#ed-length').selectOption('1');await page.locator('#ed-finger').selectOption('1');
  await page.locator('#editor-undo').click();assert.equal(await page.locator('#ed-finger').inputValue(),'');await page.locator('#editor-redo').click(); // redo intentionally clears selected note; data is restored
  await page.locator('.roll-note').click();await page.locator('#ed-pitch').selectOption('64');const box=await page.locator('.roll-note').boundingBox();await page.mouse.move(box.x+5,box.y+7);await page.mouse.down();await page.mouse.move(box.x+65,box.y-12,{steps:5});await page.mouse.up();assert.equal(await page.locator('#ed-pitch').inputValue(),'65');await page.keyboard.press('ArrowDown');assert.equal(await page.locator('#ed-pitch').inputValue(),'64');await page.screenshot({path:path.join(artifacts,'editor-v2.png'),fullPage:true});await page.locator('#ed-hand').selectOption('left');await page.locator('.roll-grid').click({position:{x:24,y:16*19+9}});await page.locator('#ed-tool').selectOption('rest');await page.locator('.roll-grid').click({position:{x:220,y:15*19+9}});await page.locator('#editor-save').click();await page.waitForSelector('#editor-dialog',{state:'hidden'});let scores=await all('scores');assert.equal(scores.length,1);assert.equal(scores[0].title,'QA 图形双手练习');assert(scores[0].notes.some(n=>n.pitch===64&&n.hand==='right'));assert(scores[0].notes.some(n=>n.pitch===null));assert(scores[0].notes.some(n=>n.hand==='left'&&n.pitch!==null));
  await page.locator('[data-filter="custom"]').click();assert.equal(await page.locator('.score-tile').count(),1);await page.screenshot({path:path.join(artifacts,'library-v2.png'),fullPage:true});await page.reload();await page.waitForSelector('#score-viewer svg');await nav('library');await page.locator('[data-filter="custom"]').click();assert.equal(await page.locator('.score-tile').count(),1);
  console.log('PASS: graphical creation, two hands, rests, properties, undo/redo and durable save');
  await page.locator('#import-button').click();await page.locator('#import-paste-tab').click();await page.locator('#json-paste').fill('{broken');await page.locator('#parse-json-paste').click();assert(await page.locator('#import-error').isVisible());assert(await page.locator('#confirm-import').isDisabled());await page.locator('#load-json-example').click();assert(await page.locator('#confirm-import').isEnabled());await page.locator('#confirm-import').click();await page.waitForSelector('#import-dialog',{state:'hidden'});assert.equal((await all('scores')).length,2);
  await page.locator('#score-file').setInputFiles(path.join(root,'examples','beginner-study.mid'));await page.waitForSelector('[data-midi-track]');assert.equal(await page.locator('[data-midi-track]').count(),2);await page.locator('[data-midi-track="1"]').selectOption('ignore');assert.match(await page.locator('#import-midi-summary').innerText(),/左手 0/);await page.locator('[data-midi-track="1"]').selectOption('left');await page.locator('#import-midi-title').fill('QA MIDI');await page.locator('#import-midi-title').dispatchEvent('input');await page.screenshot({path:path.join(artifacts,'import-v2.png'),fullPage:true});await page.locator('#confirm-import').click();await page.waitForSelector('#import-dialog',{state:'hidden'});scores=await all('scores');assert.equal(scores.length,3);assert(scores.find(s=>s.title==='QA MIDI').notes.some(n=>n.hand==='left'));
  const backup={schemaVersion:2,type:'banpai-library',scores:[scores[0]]};await page.locator('#score-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.waitForFunction(()=>!document.querySelector('#confirm-import').disabled);await page.locator('#confirm-import').click();await page.waitForSelector('#import-dialog',{state:'hidden'});assert.equal((await all('scores')).length,4);
  await page.locator('#score-file').setInputFiles({name:'bad.mid',mimeType:'audio/midi',buffer:Buffer.from('bad')});await page.waitForSelector('#import-error:not([hidden])');assert(await page.locator('#confirm-import').isDisabled());await page.locator('#import-dialog .dialog-close').click();
  console.log('PASS: JSON errors/paste, MIDI track selection, file backup restore and corrupt MIDI rejection');
  await page.locator('[data-open-score]').filter({hasText:'打开练习'}).first().click();await page.locator('.source-card summary').click();const downloadPromise=page.waitForEvent('download');await page.locator('#export-json').click();const download=await downloadPromise;assert(download.suggestedFilename().endsWith('.json'));
  await nav('library');await page.locator('[data-filter="哈农"]').click();await page.locator('[data-open-score="hanon-1"]').click();await page.locator('#end-bar').fill('1');await page.locator('#end-bar').dispatchEvent('change');await page.locator('#tempo-number').fill('240');await page.locator('#tempo-number').dispatchEvent('change');await page.locator('#loop-count').selectOption('2');await page.locator('#demo-button').click();await waitSaved(5);await page.waitForFunction(()=>document.querySelector('#capture-status').textContent.includes('结束'));assert.equal((await all('takes')).filter(t=>t.source==='demo').length,3);
  console.log('PASS: export and automatic two-round range loop saves separate takes');
  await page.evaluate(()=>{const device={id:'mock-piano',name:'QA Piano',state:'connected',onmidimessage:null,open:async()=>{}};const access={inputs:new Map([[device.id,device]]),onstatechange:null};window.testDevice=device;window.testAccess=access;Object.defineProperty(navigator,'requestMIDIAccess',{configurable:true,value:async()=>access});});await page.locator('#connect-button').click();await page.waitForFunction(()=>document.querySelector('#device-pill').textContent==='已连接');await page.evaluate(()=>testDevice.onmidimessage({data:new Uint8Array([0x90,60,100])}));assert.match(await page.locator('#input-note').innerText(),/C4/);await page.locator('#tempo-number').fill('120');await page.locator('#tempo-number').dispatchEvent('change');await page.locator('#start-button').click();await page.waitForFunction(()=>document.querySelector('#capture-status').textContent.includes('正在采集'));await page.evaluate(()=>{testDevice.onmidimessage({data:new Uint8Array([0x90,60,100])});testDevice.onmidimessage({data:new Uint8Array([0x90,60,0])});testDevice.state='disconnected';testAccess.inputs.clear();testAccess.onstatechange();});await waitSaved(6);const midi=(await all('takes')).find(t=>t.source==='midi');assert.equal(midi.events.length,1);assert.equal(midi.reason,'设备断开');assert.equal(await page.locator('#device-pill').innerText(),'未连接');
  await page.evaluate(()=>Object.defineProperty(navigator,'requestMIDIAccess',{configurable:true,value:undefined}));await page.locator('#connect-button').click();assert.match(await page.locator('#device-description').innerText(),/不支持/);
  console.log('PASS: mock Web MIDI permission/device/note-on/note-off/disconnect; unsupported browser guidance');
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(artifacts,'mobile-v2.png'),fullPage:true});await nav('library');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#create-score').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#editor-close').click();
  console.log('PASS: 390px responsive practice, library and editor without page overflow');
  assert.deepEqual(errors,[]);console.log('PASS: no browser JavaScript errors');
 }finally{await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
