// Regression checks for imported metadata, cross-bar editing and old-record migration.
const {chromium}=require('playwright'),{spawn}=require('node:child_process'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
(async()=>{const server=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:'3190'},stdio:['ignore','pipe','pipe']});await new Promise(r=>server.stdout.once('data',r));const browser=await chromium.launch({executablePath:process.env.QA_CHROMIUM||undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process','--disable-gpu']});const errors=[];try{const page=await browser.newPage({viewport:{width:1440,height:950}});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:3190');await page.waitForSelector('#score-viewer svg');
 const open=async score=>{await page.evaluate(async score=>{const {openScoreEditor}=await import('/editor.mjs');window.savedEditor=null;openScoreEditor(score,{onSave:async value=>{window.savedEditor=value;}});},score);await page.waitForSelector('#editor-sheet svg');};
 const base={schemaVersion:2,id:'long-note',title:'Long note',composer:'',collection:'custom',bpm:72,timeSignature:[4,4],keySignature:'F#m',notes:[{id:'long',pitch:60,beat:3,duration:4,hand:'right'}],totalBeats:8};
 await open(base);assert.equal(await page.locator('#ed-key').inputValue(),'F#m');await page.locator('#ed-copybar').click();await page.locator('#editor-save').click();await page.waitForSelector('#editor-dialog',{state:'hidden'});const copied=await page.evaluate(()=>savedEditor);assert.equal(copied.totalBeats,12);assert(copied.notes.some(n=>n.beat===7&&n.duration===4));console.log('PASS: copying cross-bar sustained notes extends the score before saving');
 await open({...base,timeSignature:[7,8],notes:[{id:'a',pitch:61,beat:0,duration:1,hand:'right'}],totalBeats:7});assert.equal(await page.locator('#ed-meter').inputValue(),'7/8');assert.equal(await page.locator('#ed-key').inputValue(),'F#m');await page.locator('#editor-save').click();const odd=await page.evaluate(()=>savedEditor);assert.deepEqual(odd.timeSignature,[7,8]);assert.equal(odd.keySignature,'F#m');console.log('PASS: imported uncommon meter and key remain visible and preserved');
 await page.evaluate(()=>{localStorage.removeItem('banpai-v1-migrated');localStorage.setItem('banpai-practices-v1',JSON.stringify([{id:'old-1',exerciseId:'joy',bpm:80,source:'virtual',date:new Date().toISOString(),events:[{pitch:64,time:.03,duration:.4,velocity:80}],elapsed:2,interrupted:true,reason:'主动结束'},{id:'corrupt',exerciseId:'joy',bpm:80,source:'virtual',date:new Date().toISOString(),events:[null]}]));});await page.reload();await page.waitForFunction(()=>document.querySelector('#history-count').textContent==='1');let takes=await page.evaluate(async()=>{const {readAll}=await import('/storage.mjs');return readAll('takes');});assert.equal(takes.length,1);assert.equal(takes[0].id,'legacy-old-1');assert(takes[0].legacy);await page.reload();await page.waitForFunction(()=>document.querySelector('#history-count').textContent==='1');takes=await page.evaluate(async()=>{const {readAll}=await import('/storage.mjs');return readAll('takes');});assert.equal(takes.length,1);await page.locator('[data-view="history"]').click();await page.locator('.history-row').click();assert.match(await page.locator('#feedback-content').innerText(),/旧版记录/);console.log('PASS: valid legacy take migrates once; corrupt entry is skipped; history remains inspectable');
 await page.locator('[data-view="history"]').click();await page.locator('#clear-history').click();await page.locator('#confirm-cancel').click();assert.equal(await page.locator('.history-row').count(),1);await page.locator('#clear-history').click();await page.locator('#confirm-ok').click();await page.waitForFunction(()=>document.querySelector('#history-count').textContent==='0');await page.reload();await page.waitForSelector('#score-viewer svg');takes=await page.evaluate(async()=>{const {readAll}=await import('/storage.mjs');return readAll('takes');});assert.equal(takes.length,0);assert.deepEqual(errors,[]);console.log('PASS: clearing history honors cancel, then clears migrated source without resurrection');
 }finally{await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
