// Optional browser acceptance. Install Playwright locally or provide NODE_PATH / QA_CHROMIUM.
const {chromium}=require('playwright');
const {spawn}=require('node:child_process');
const {mkdirSync,readFileSync}=require('node:fs');
const path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),artifacts=path.join(root,'artifacts');mkdirSync(artifacts,{recursive:true});
(async()=>{
 const server=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:'3192'},stdio:['ignore','pipe','pipe']});
 await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);});
 const browser=await chromium.launch({executablePath:process.env.QA_CHROMIUM||undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process','--disable-gpu']});
 const context=await browser.newContext({viewport:{width:1440,height:1050}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const all=store=>page.evaluate(async store=>(await import('/storage.mjs')).readAll(store),store);
 const nav=async name=>page.locator(`[data-view="${name}"]`).click();
 const poll=async(fn,label)=>{const end=Date.now()+15000;while(!await fn()){if(Date.now()>end)throw Error('Timed out: '+label);await page.waitForTimeout(60);}};
 const save=async()=>{await page.locator('#progress-dialog-save').click();await page.waitForSelector('#progress-dialog',{state:'hidden'});};
 const upload=async data=>{await page.locator('#progress-file').setInputFiles({name:'progress.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});};
 try{
  await page.goto('http://127.0.0.1:3192');await page.waitForSelector('#score-viewer svg');await poll(async()=>(await all('settings')).length===1,'settings initialized');await nav('progress');
  assert.match(await page.locator('.progress-metrics').innerText(),/完整采集后开始累计/);assert.equal(await page.locator('.progress-ring strong').innerText(),'0%');await page.screenshot({path:path.join(artifacts,'progress-empty-v3.png'),fullPage:true});
  const clean=JSON.stringify(await all('settings'));await page.locator('#preview-progress').click();assert(await page.locator('.demo-banner').isVisible());assert.equal(await page.locator('#nav-progress-count').innerText(),'0%');assert.equal((await all('activities')).length,0);assert.equal(JSON.stringify(await all('settings')),clean);await page.screenshot({path:path.join(artifacts,'progress-example-v3.png'),fullPage:true});await page.locator('#exit-progress-demo').click();
  await page.locator('#progress-settings').click();await page.locator('#goal-grade').selectOption('2');await page.locator('#goal-minutes').fill('150');await save();assert.match(await page.locator('.hero-main h2').innerText(),/2 级/);
  await page.locator('.journey-heading [data-new-log]').click();await page.locator('#log-title').fill('599 慢练 <练习笔记>');await page.locator('#log-minutes').fill('30');await page.locator('#log-note').fill('第二小节分手练习');await save();assert.equal((await all('activities')).length,1);assert.match(await page.locator('.progress-metrics article').first().innerText(),/30/);assert.match(await page.locator('.progress-metrics article').last().innerText(),/—/);
  await page.locator('[data-edit-log]').click();await page.locator('#log-minutes').fill('45');await save();assert.equal((await all('activities')).length,1);assert.equal((await all('activities'))[0].seconds,2700);assert.match(await page.locator('#today-summary').innerText(),/45/);
  await page.locator('[data-progress-tab="levels"]').click();assert.equal(await page.locator('.grade-stop').count(),5);assert.equal(await page.locator('.skill-task').count(),12);await page.locator('[data-route-grade="2"]').click();await page.locator('[data-check-id="g2-technique-1"]').click();await page.locator('#check-state').selectOption('done');await page.locator('#check-origin').selectOption('teacher');await page.locator('#progress-dialog-save').click();assert(await page.locator('#progress-error').isVisible());await page.locator('#check-note').fill('老师反馈：慢速均匀，可以继续巩固。');await save();assert.equal(await page.locator('#nav-progress-count').innerText(),'8%');await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(artifacts,'levels-v3.png'),fullPage:true});
  await page.locator('[data-progress-tab="plans"]').click();await page.locator('.section-heading [data-new-plan]').click();await page.locator('#plan-title').fill('我的纸谱计划');await save();assert.equal(await page.locator('.plan-card').count(),1);assert.match(await page.locator('.plan-evidence').innerText(),/纸谱计划/);
  await page.locator('.section-heading [data-new-plan]').click();await page.locator('#plan-score').selectOption('joy');assert.equal(await page.locator('#plan-hand').inputValue(),'right');await page.locator('#plan-bpm').fill('90');await save();assert.equal(await page.locator('.plan-card').count(),2);await page.locator('[data-practice-plan]').last().click();assert.equal(await page.locator('#breadcrumb').innerText(),'练习室');assert.equal(await page.locator('#tempo-number').inputValue(),'90');
  await nav('progress');const downloadPromise=page.waitForEvent('download');await page.locator('#export-progress').click();const download=await downloadPromise,backup=JSON.parse(readFileSync(await download.path(),'utf8'));assert.equal(backup.activities.length,1);assert.equal(backup.learning.plans.length,2);
  await page.reload();await page.waitForSelector('#score-viewer svg');await nav('progress');assert.equal(await page.locator('#nav-progress-count').innerText(),'8%');assert.match(await page.locator('#today-summary').innerText(),/45/);await page.locator('[data-delete-log]').click();await page.locator('#confirm-ok').click();await poll(async()=>(await all('activities')).length===0,'delete manual');
  await upload(backup);await page.waitForSelector('#confirm-dialog[open]');await page.locator('#confirm-cancel').click();assert.equal((await all('activities')).length,0);await upload(backup);await page.waitForSelector('#confirm-dialog[open]');await page.locator('#confirm-ok').click();await poll(async()=>(await all('activities')).length===1,'restore');await upload(backup);await page.waitForSelector('#confirm-dialog[open]');assert.match(await page.locator('#confirm-text').innerText(),/新增 0/);await page.locator('#confirm-ok').click();await page.waitForSelector('#confirm-dialog',{state:'hidden'});assert.equal((await all('activities')).length,1);
  const before=JSON.stringify(await all('activities'));await upload({...backup,activities:[...backup.activities,...backup.activities]});await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('重复的练习'));assert.equal(JSON.stringify(await all('activities')),before);assert(!await page.locator('#confirm-dialog').isVisible());
  console.log('PASS: empty/example states, goals, manual notes, teacher evidence, plans, reload and idempotent backup restore');
  // A short genuine virtual-input take follows the same acquisition path as MIDI.
  await nav('practice');await page.locator('#virtual-button').click();await page.locator('#tempo-number').fill('120');await page.locator('#tempo-number').dispatchEvent('change');await page.locator('#end-bar').fill('1');await page.locator('#end-bar').dispatchEvent('change');await page.locator('#start-button').click();await page.waitForFunction(()=>document.querySelector('#capture-status').textContent.includes('正在采集'));await page.keyboard.press('a');await poll(async()=>(await all('takes')).length===1,'virtual capture saved');await poll(async()=>(await all('activities')).length===2,'summary saved atomically');const activity=(await all('activities')).find(a=>a.kind==='capture');assert.equal(activity.source,'virtual');assert.equal(activity.whole,false);assert.equal(activity.complete,true);assert(activity.startedAt);
  await page.locator('#demo-button').click();await poll(async()=>(await all('takes')).length===2,'demo saved');assert.equal((await all('activities')).length,2);
  await nav('progress');await page.screenshot({path:path.join(artifacts,'progress-personal-v3.png'),fullPage:true});
  for(const width of [1024,768,390]){await page.setViewportSize({width,height:900});await page.locator('[data-progress-tab="overview"]').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overview width '+width);await page.locator('[data-progress-tab="levels"]').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'levels width '+width);await page.locator('[data-progress-tab="plans"]').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'plans width '+width);}
  await page.locator('[data-progress-tab="overview"]').click();await page.evaluate(()=>scrollTo(0,0));await page.locator('#toast.visible').waitFor({state:'hidden',timeout:7000});await page.screenshot({path:path.join(artifacts,'progress-mobile-v3.png'),fullPage:true});await page.setViewportSize({width:1440,height:1050});
  console.log('PASS: virtual input generates persistent summary; demos excluded; 1024/768/390px layouts fit');
  // Existing v1 database migration: 105 detailed takes must backfill before retaining only the newest 100.
  const migrationContext=await browser.newContext({viewport:{width:1440,height:1050}}),migration=await migrationContext.newPage();migration.on('pageerror',e=>errors.push(e.message));await migration.goto('http://localhost:3192/favicon.svg');
  await migration.evaluate(async()=>{
   const {REPERTOIRE}=await import('/repertoire.mjs'),{normalizeScore,scoreToTimedNotes,scoreDuration,barCount}=await import('/score-model.mjs');const score=normalizeScore(REPERTOIRE.find(s=>s.id==='joy')),options={bpm:120,hand:'right',startBar:1,endBar:barCount(score)};
   await new Promise((resolve,reject)=>{const request=indexedDB.open('banpai-studio-v2',1);request.onupgradeneeded=()=>{request.result.createObjectStore('scores',{keyPath:'id'});request.result.createObjectStore('takes',{keyPath:'id'});};request.onsuccess=()=>{const db=request.result,tx=db.transaction(['scores','takes'],'readwrite');tx.objectStore('scores').put({...score,id:'custom-preserved',title:'Keep my score'});for(let i=0;i<105;i++)tx.objectStore('takes').put({schemaVersion:2,id:'old-'+i,score,options,bpm:120,source:'midi',date:new Date(Date.now()-i*120000).toISOString(),events:scoreToTimedNotes(score,options),elapsed:scoreDuration(score,options),interrupted:false});tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(new Error('Migration transaction: '+tx.error));};request.onerror=()=>reject(new Error('Migration open: '+request.error));});
  });
  await migration.goto('http://localhost:3192');await migration.waitForSelector('#score-viewer svg');const migrated=store=>migration.evaluate(async store=>(await import('/storage.mjs')).readAll(store),store);const end=Date.now()+15000;while((await migrated('takes')).length!==100){if(Date.now()>end)throw Error('Migration prune timeout');await migration.waitForTimeout(60);}assert.equal((await migrated('activities')).length,105);assert.equal((await migrated('scores')).length,1);await migration.reload();await migration.waitForSelector('#score-viewer svg');assert.equal((await migrated('activities')).length,105);
  await migration.locator('[data-view="history"]').click();await migration.locator('#clear-history').click();await migration.locator('#confirm-ok').click();await migration.waitForFunction(()=>document.querySelector('#history-count').textContent==='0');assert.equal((await migrated('activities')).length,0);assert.equal((await migrated('scores')).length,1);assert.equal((await migrated('settings')).length,1);
  console.log('PASS: v1 database upgrade preserves custom score, archives all 105 takes before 100-take pruning; clear keeps learning settings');
  await page.evaluate(async()=>{const {writeBatch,readAll}=await import('/storage.mjs');try{await writeBatch([{store:'activities',value:{id:'must-rollback'}},{store:'settings',value:{id:'bad-clone',f:()=>{}}}]);throw new Error('Should have failed');}catch(error){if(error.message==='Should have failed')throw error;}if((await readAll('activities')).some(a=>a.id==='must-rollback'))throw new Error('Partial transaction survived');});
  console.log('PASS: synchronous clone failure rolls back the entire multi-store transaction');
  // A corrupt learning record must not lead to a deceptively empty backup.
  await page.evaluate(async()=>{const {putRecord}=await import('/storage.mjs');await putRecord('settings',{id:'learning',targetGrade:99});});await page.reload();await page.waitForSelector('#score-viewer svg');await nav('progress');await page.waitForSelector('.storage-warning');assert(await page.locator('#export-progress').isDisabled());assert(await page.locator('#progress-settings').isDisabled());
  assert.deepEqual(errors,[]);console.log('PASS: storage error is explicit and complete backup is disabled; no browser JavaScript errors');
 }finally{await browser.close();server.kill('SIGTERM');}
})().catch(e=>{console.error(e);process.exit(1);});
